insert into vocabulary (word_type, word_en, word_kr) values ('M', 'culture', '"문화,교양"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'experience', '경험');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'education', '교육');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'symbol', '상징');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'effect', '"결과,영향,효과"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'liberty', '자유');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'affair', '"사건,일"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'comfort', '"안락,위안"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'tradition', '"전통,전설"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'subject', '"학과,주제,주어"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'object', '"사물,목적, 반대하다"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'source', '"출처,근원"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'revloution', '혁명');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'pollution', '오염');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'system', '"조직,체계,지도"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'triumph', '승리');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'respect', '"존경, 존경하다"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'examination', '"시험,조사"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'foundation', '기초');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'glory', '영광');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'situation', '"위치,사태"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'competition', '경쟁');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'prairie', '대초원');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'effort', '노력');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'library', '도서관');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'rein', '고삐');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'solution', '"해결,용해"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'hono(u)r', '"명예/경의, 존경하다"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'unity', '통일/일치');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'population', '인구');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'direction', '"방향,지시"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'factory', '공장');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'repiblic', '공화국');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'method', '방법');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'increase', '"증가, 증가하다"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'decrease', '"감소, 감소하다"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'amount', '"양,액수,총계"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'ancestor', '"조상,선조"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'voyage', '항해');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'sculpture', '조각(품)');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'instrument', '"기계, 기구, 도구"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'figure', '"숫자, 계산, 모습, 인물"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'activity', '활동');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'cause', '"원인, 이유"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'worth', '"가치, ~에 가치가 있는"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'accident', '"사고, 뜻밖의 사건"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'adventure', '모험');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'view', '"경치, 의견"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'relative', '"친척, 관계가 있는"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'superstition', '미신');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'habit', '"습관, 버릇"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'wealth', '"재산, 부"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'treasure', '보물');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'universe', '"우주, 전세계의"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'adult', '"성인, 성인으"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'feast', '"향연, 잔치"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'resources', '"자원, 수단"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'ruin', '파멸');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'monument', '"기념비, 기념물"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'information', '"정보, 지식, 통지"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'appetite', '식욕');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'stethoscope', '청진기');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'mystery', '"신비, 불가사의"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'thermometer', '온도계');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'burden', '"무거운 짐, 짐을 지우다"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'series', '"연속, 시리즈"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'oath', '"맹세, 선서"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'appointment', '"임명, 약속"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'clue', '"실마리, 단서"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'debt', '"은혜, 빚"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'hydrogen', '수소');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'control', '"통제, 지배, 통제하다"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'uniform', '"제복, 한 모양의"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'design', '"계획(하다), 설계(하다)"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'damage', '"손해, 손상"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'custom', '"습관, 풍습"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'traffic', '교통');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'sophomore', '2학년생');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'temperature', '"온도, 체온"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'limit', '"제한하다, 한계, 제한"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'statue', '조각상');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'furniture', '가구');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'parade', '행렬');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'public', '"공중(사회), 공공의, 공중의"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'pilgrim', '순례자');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'greeting', '"인사, 축하"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'language', '언어');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'opinion', '의견');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'athlete', '운동 선수');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'supply', '"공급, 공급하다"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'surface', '표면');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'electricity', '전기');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'order', '"순서, 명령"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'spirit', '정신');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'purpose', '목적');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'promise', '"가망, 전망, 약속"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'project', '"계획, 계획하다"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'government', '"정부, 정치의"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'exercise', '"운동, 연습하다"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'comparison', '비교[100]');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'interest', '"이익, 흥미"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'funeral', '장례식');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'senior', '"선배, 손위에"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'junior', '"후배,손아래에"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'democracy', '"민주주의,민주정치"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'general', '육군장군');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'admiral', '해군대장');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'edge', '"날,가장자리"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'biology', '생물학');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'danger', '위험');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'advice', '충고');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'practice', '연습하다');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'mammal', '포유동물');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'grade', '학년');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'score', '점수');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'pause', '"중지,멈추다"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'pronaunciation', '발음');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'stress', '"압박,강조하다"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'contest', '경쟁');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'horizon', '수평선의');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'principal', '수평선의');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'might', '힘');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'trouble', '"고생,걱정하다"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'scar', '상처');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'balance', '균형');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'proverb', '속담');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'semester', '학기');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'election', '선거');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'inning', '회');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'hollw', '"구멍,우묵한곳"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'degree', '"도,정도"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'cemetery', '묘지');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'relay', '"교대자,교대하다"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'spot', '지점');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'exchange', '교환하다');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'merchant', '상인');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'saying', '격언');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'refrigerator', '냉장고');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'crack', '갈라진 틈');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'judge', '재판관');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'slave', '노예');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'sttler', '이주민');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'fare', '요금');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'gesture', '몸짓');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'planet', '유성');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'type', '유형');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'secretary', '비서');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'devil', '악마');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'schola', '학자');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'pardon', '용서');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'kindergarten', '유치원');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'detective', '탐정');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'license', '면허');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'palace', '궁전');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'spade', '삽');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'square', '정가각형');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'fountain-pen', '만년필');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'harvest', '수확');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'tool', '도구');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'sword', '칼');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'magazine', '잡지');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'stadium', '경기장');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'care', '걱정');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'beauty', '아름다움');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'museum', '박물관');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'sentence', '문장');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'memory', '기억');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'delight', '기쁨');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'passenger', '승객');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'skill', '숙련');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'journey', '여행');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'ceremony', '의식');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'hobby', '취미');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'president', '대통령');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'address', '주소');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'continent', '대륙');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'mankind', '인간');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'patient', '환자');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'site', '부지');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'marble', '대리석');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'stem', '줄기');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'slip', '미끄러짐');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'torch', '횃불');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'composer', '작곡가');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'invader', '침입자');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'trick', '계략');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'flight', '비행');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'castle', '성');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'envelope', '봉');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'pal', '친구');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'vacation', '휴가');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'desert', '사막');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'event', '사건');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'therter', '극장');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'stage', '무대');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'error', '잘못');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'area', '"면적, 지역"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'base', '"기초, 기초를 두다"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'basement', '지하실');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'evil', '"악, 나쁜"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'atom', '원자');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'poet', '시인');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'petal', '꽃잎');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'chance', '"기회, 가능성"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'mind', '마음');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'climate', '"기후, 풍토"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'suburb', '교외');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'throat', '목구멍');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'voice', '목소리');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'valley', '"골짜기, 계곡"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'puritan', '청교도');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'feather', '깃털');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'amateur', '아마추어');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'nation', '국가');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'puzzle', '수수께끼');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'riddle', '수수께끼');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'rear', '뒤쪽');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'battle', '"전투, 싸움"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'laundry', '세탁소');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'shower', '"소나기, 샤워"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'navy', '해군');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'mars', '화성');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'gallery', '화랑');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'guest', '손님(visitor)');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'folk', '사람들');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'problem', '문제');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'jewel', '보석');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'garage', '차고');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'fault', '"결점, 잘못"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'lantern', '랜턴');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'import', '수입(품)');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'angle', '각도');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'match', '시합');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'stripe', '줄무늬');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'pulse', '맥박');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'powder', '"가루,화약"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'flood', '홍수');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'bush', '"수풀,덤불"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'branch', '가지');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'hero', '"영웅, 복수 : heroes"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'heaven', '하늘');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'exit', '출구');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'beast', '짐승(=animal)');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'century', '"세기,100년"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'coeducation', '"남녀,공학"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'twin', '쌍둥이의 한 사람');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'wound', '"상처,부상"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'metal', '금속');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'insect', '곤충');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'track', '"지나간자국,선로"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'deserve', '"받을가치가있다,~할 만하다"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'survive', '"~보다 오래 살다, ~에서 살아남다"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'create', '창조하다');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'describe', '묘사하다');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'select', '"고르다,선발한"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'hesitate', '"주저하다,망설이다"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'declare', '선언하다');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'pretend', '~인 체하다');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'struggle', '"분투, 노력하다, 싸우다"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'explore', '탐험하다');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'astonish', '놀라게 하다');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'disappoint', '실망시키다');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'attract', '끌다');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'celebrate', '축하하다');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'explode', '폭발시키다');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'include', '포함하다');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'protect', '보호하다');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'introduce', '"소개하다,도입하다"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'produce', '생산하다');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'chase', '"쫓다,추적"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'scratch', '"할퀴다,긁다"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'jar', '항아리');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'stare', '응시하다');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'gaze', '"응시하다,바라보다"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'scare', '"놀라게하다,놀라다"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'grab', '움켜잡다');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'guard', '"지키다,경계,위병"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'discuss', '토론하다');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'shrug', '어깨를 으쓱하다');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'sniff', '냄새맡다');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'scream', '날카롭게 소리치다');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'rid', '제거하다');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'surround', '둘러싸다.');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'cleave', '"쪼개다, 찢다"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'carve', '"새기다, 조각하다"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'except', '제외하다');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'invent', '발명하다');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'search', '찾다');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'abuse', '"남용하다, 학대하다"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'owe', '"힘입다, 빚(의무)이 있다"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'bless', '축복하다');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'graduate', '졸업하다');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'replace', '"~을 대신하다, 제 자리에 놓다"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'collect', '"모으다, 수집하다"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'upset', '"뒤엎다, 당황하게 하다"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'arrest', '"체포하다, 체포"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'prove', '증명하다');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'yell', '외치다');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'howl', '"짖다, 울부짖다"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'halt', '정지하다[300]');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'leak', '새다');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'behave', '행동하다');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'wrap', '싸다');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'locate', '위치하다');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'charge', '청구하다');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'review', '복습하다');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'refuse', '거절하다');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'complain', '불평하다');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'remain', '남다');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'warn', '경고하다');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'bend', '구부리다');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'suffer', '겪다');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'whisper', '속삭이다');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'prepare', '준비하다');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'roar', '으르렁거리다');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'float', '뜨다');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'drag', '질질끌다');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'overhear', '엿듣다');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'slide', '미끄러지다');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'suck', '빨다');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'bother', '괴롭히다');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'deal', '분배하다');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'treat', '다루다');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'destroy', '파괴하다');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'accept', '받아들이다');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'depend', '~에 의존하다');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'nod', '끄덕이다');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'remove', '옮기다');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'beat', '때리다');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'clap', '탁 치다');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'feed', '먹을 것을 주다');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'obtain', '얻다');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'drown', '"빠뜨리다, 빠지다, 빠져죽다"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'remind', '생각나게 하다');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'occur', '일어나다');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'ache', '아프다');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'repeat', '되풀이하다');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'attend', '참석하다');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'sigh', '한숨쉬다');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'pray', '빌다');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'press', '누르다');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'bear', '낳다');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'follow', '따르다');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'hate', '미워하다');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'frighten', '깜짝놀라게 하다');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'shout', '외치다');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'mention', '말하다');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'waste', '낭비하다');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'borrow', '빌리다');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'complete', '완성하다');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'excellent', '뛰어난');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'competent', '유능한');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'religious', '종교적인');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'favorite', '아주 좋아하는');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'entire', '전체의');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'primary', '본래의');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'similar', '비슷한');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'precious', '귀중한');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'normal', '보통의');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'popular', '인기있는');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'compulsory', '의무적인');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'curious', '호기심이 강한');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'independent', '독립의');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'intimate', '친밀한');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'delicious', '맛있는');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'valuable', '귀중한');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'grave', '중대한');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'elementary', '초보의');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'crazy', '미친');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'contrary', '반대의');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'regular', '규칙적인');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'social', '사회의');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'straight', '똑바른');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'noble', '고귀한');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'anxious', '걱정되는');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'international', '국제적인');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'greedy', '탐욕스러운');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'stupid', '어리석은');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'silly', '어리석은');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'lonely', '고독한');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'dirty', '더러운');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'various', '여러가지의');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'private', '개인의');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'vain', '무익한');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'sore', '아픈');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'fierce', '사나운');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'fifm', '굳은');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'solar', '태양의');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'smart', '산뜻한');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'single', '독신의');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'diligent', '부지런한');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'serious', '진지한');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'fresh', '새로운');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'empty', '빈');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'mild', '온화한');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'amazing', '놀라운');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'charming', '매력적인');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'boring', '지겨운');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'giant', '거대한');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'huge', '거대한[400]');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'tiny', '몹시 작은');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'fair', '공명정대한');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'tough', '단단한');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'foreign', '외국의');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'modern', '현대의');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'expensive', '값비싼');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'harmful', '해로운');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'calm', '평온한');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'special', '특별한');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'steady', '확고한');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'hay', '건초');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'revival', '부활');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'million', '백만');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'crop', '농작물');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'shade', '그늘');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'company', '친구');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'canal', '운하');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'wagon', '짐마차');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'fact', '사실');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'joy', '기쁨');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'concert', '음악회');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'rule', '규정하다');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'suitcase', '여행가방');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'weight', '무게');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'hurray', '만세');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'mail', '우편물');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'log', '통나무');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'hut', '오두막집');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'tax', '세금');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'dye', '물감');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'earnings', '벌이');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'flame', '불꽃');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'shape', '모양');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'chest', '가슴');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'chain', '사슬');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'cost', '비용');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'coast', '해안');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'sircle', '"원,집단"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'heart', '심장');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'nature', '자연');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'fever', '열');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'tongue', '혀');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'trust', '신용');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'whisker', '구레나룻');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'prison', '형무소');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'blood', '피');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'loaf', '빵 한 덩어리');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'list', '명부');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'fence', '울타리');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'enemy', '적');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'thief', '도둑');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'data', '자료');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'soldier', '"군인,병사"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'musician', '음악가');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'capital', '"수도, 자본"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'course', '"진로, 과정"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'diary', '일기');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'squirrel', '다람쥐');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'dawn', '새벽');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'shadow', '그림자');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'ditch', '도랑');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'crew', '승무원');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'stomach', '위');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'neighbor', '이웃사람');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'servant', '하인');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'hunger', '굶주림');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'tomb', '"묘, 무덤"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'taste', '"맛, 취미"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'sign', '"신호, 구호"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'stair', '계단');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'trip', '여행');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'brain', '"뇌,머리"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'trumphet', '나팔');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'speech', '"말,연설"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'thumb', '엄지손가락');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'horn', '"뿔, 경적"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'chief', '"우두머리, 주요한"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'trousers', '바지');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'prince', '왕자');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'force', '"힘, 강요하다"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'sight', '"광경,경치"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'space', '"공간,우주"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'wool', '양모');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'expressway', '고속도로');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'science', '과학');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'nephew', '조카');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'niece', '조카딸');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'salt', '소금');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'death', '"죽음,사망"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'saw', '"톱, 톱으로 켜다"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'swing', '"그네,진동"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'wish', '"소원, 원하다"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'grain', '"곡식, 낱알"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'eraser', '지우개');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'alphabet', '알파벳 문자');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'shoulder', '어깨');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'communication', '전달/교통');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'section', '"부분,구역"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'dialog(ue)', '대화');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'crash', '"충돌[추락](하다), 와르르 무너지다"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'giraffe', '기린');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'hawk', '매');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'pigeon', '비둘기');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'bowl', '"사발, 그릇"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'scene', '"장면, 현장"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'life', '"생명, 생활"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'earth', '"지구, 땅"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'pill', '알약');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'math', '수학');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'ocean', '대양');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'price', '"값, 가격"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'row', '"줄, 열"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'schedule', '예정표');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'machine', '기계');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'route', '길');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'ivy', '담쟁이 덩굴');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'gift', '"선물, 타고난 재능"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'candle', '"양초, 촛불"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'joke', '"농담, 농담을 하다"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'art', '"예술, 미술"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'corn', '곡물');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'pet', '"애완동물, 귀여워하는"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'robber', '강도');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'cheek', '볼');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'clerk', '"사무원, 점원"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'cookie', '"쿠키, 맛인는 작은 과자"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'army', '"육군, 군대"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'nurse', '간호사');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'master', '"주인, 정복하다"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'lock', '"자물쇠, 좌물쇠를 채우다"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'moment', '순간');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'sheet', '"침대의 시트, 종이 한장"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'monk', '승려');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'teenager', '10대 소년소녀');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'closet', '벽장');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'handle', '손잡이');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'guide', '"안내자, 안내하다"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'bar', '"막대기, 빗장"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'ostrich', '"타조, 방관자"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'knee', '무릎');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'cricket', '크리켓 경기');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'deck', '갑판');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'bit', '"작은 조각, 조금"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'silk', '비단');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'jean', '"진바지, 진으로 만든 옷"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'cotton', '"솜, 면화"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'drum', '북');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'sand', '"모래, 모래밭"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'shock', '"충격, 충격을 주다"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'march', '"행진, 행진하다"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'cage', '"새장, 우리"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'whole', '"전부, 전부의"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'change', '"변화, 잔돈"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'department', '"부, 백화점의 매장"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'office', '"사무실, 회사"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'ticket', '"표, 입장권"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'energy', '"힘, 활기"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'idea', '"생각, 이념"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'hospital', '병원');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'noise', '"소리, 소음"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'sample', '견본');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'example', '"예, 보기"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'lesson', '"학과, 교훈"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'plenty', '"풍부, 많은"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'luck', '행운');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'comedy', '"희극, 코미디"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'health', '건강');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'history', '역사');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'forest', '숲');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'stream', '"흐름, 흐르다"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'future', '"미래,"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'state', '"상태, 국가"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'temple', '"절, 사원"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'dictionary', '사전');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'grammar', '문법');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'college', '"단과대학, 전문학교"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'husband', '남편');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'daughter', '딸');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'captain', '"우두머리, 선장"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'booth', '"오두막집, 작은 방"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'iceberg', '빙산');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'bubble', '거품');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'bottom', '"밑, 밑바닥"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'prize', '"상, 상품"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'bean', '콩');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'race', '"경주, 민족"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'engineer', '"기사, 공학자"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'photographer', '사진사');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'reason', '"이유, 이성"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'subway', '"지하도, 지하철"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'fog', '안개');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'answer', '"대답, 대답하다"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'dinning room', '식당');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'step', '"걸음, 걷다"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'heat', '"열, 더위"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'bone', '뼈');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'plant', '"식물, 식물을 심다"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'lamb', '새끼양');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'rate', '"비율, 속도"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'report', '"보고, 보고하다"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'tuttle', '바다거북');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'bay', '만');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'holiday', '"휴일, 휴가"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'center', '"중심, 중심지"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'cash', '"현금, 현금으로 바꾸다"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'wolf', '"이리, 늑대"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'operator', '교환수');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'fur', '"부드러운 털, 모피"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'shore', '"물가, 바닷가"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'owl', '올빼미');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'hunter', '사냥군');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'pumpkin', '호박');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'handshake', '악수');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'bike', '자전거');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'beach', '해안');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'god', '신');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'cough', '"기침, 기침을 하다"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'shell', '조개');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'business', '"사업, 일"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'restaurant', '식당');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'sheep', '양');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'officer', '"공무원, 장교"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'hometown', '고향');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'coil', '"코일, 감긴 것"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'ceiling', '천장');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'turkey', '칠면조');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'towel', '"수건, 타월"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'matter', '"일, 문제"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'chopstick', '젓가락');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'seat', '"좌석, 앉히다"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'board', '판자');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'goal', '"목표, 골"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'drugstore', '약국');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'rat', '"쥐,들쥐"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'butterfly', '나비');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'flute', '"플룻, 피리"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'couple', '"한쌍, 커플"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'beer', '맥주');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'background', '배경');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'bottle', '병');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'body', '"몸, 신체"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'group', '집단');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'village', '마을');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'beef', '쇠고기');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'load', '"짐, 부담"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'coin', '"동전, 화폐"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'bookstore', '서점');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'label', '"꼬리표, 딱지"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'port', '항구');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'quarter', '"4분의 1, 15분"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'sunrise', '해돋이');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'sunshine', '햇빛');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'wedding', '"결혼, 결혼식"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'crown', '왕관');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'seed', '"씨, 씨를 뿌리다"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'coal', '석탄');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'comb', '"빗, 빗질하다"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'dream', '"꿈, 꿈을 꾸다"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'sugar', '설탕');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'mile', '마일');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'flashlight', '"카메라의 플랫, 회중전등"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'vegetable', '야채');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'mouse', '생쥐');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'wood', '"나무, 숲"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'war', '전쟁');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'ground', '"땅, 운동장"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'belt', '"띠, 허리띠"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'tourist', '"여행자, 관광객"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'airport', '공항');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'passport', '여권');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'plate', '접시');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'stone', '돌');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'downtown', '번화가');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'cousin', '사촌');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'tooth', '이');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'potato', '감자');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'blanket', '담요');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'creek', '시냇물');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'nail', '"손톱, 발톱"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'letter', '"편지, 문자"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'date', '"날짜, 데이트, 약속"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'store', '"가게, 저축하다"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'beggar', '거지');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'bedside', '~ 옆에');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'deer', '사슴');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'bill', '"계산서, 지폐"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'doll', '인형');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'pepper', '후추');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'frog', '개구리');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'rest', '"휴식, 나머지"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'tower', '탑');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'bridge', '다리');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'cloth', '"천, 직물"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'post', '"우편, 우편물"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'snake', '뱀');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'job', '"직업, 일"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'town', '"읍, 도시"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'fun', '"놀이, 재미"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'bathroom', '욕실');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'tail', '꼬리[700]');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'mayor', '시장');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'piece', '한 조각');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'fruit', '과일');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'british', '"영국인, 영국의"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'french', '"프랑스 사람, 프랑스어"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'German', '"독일사람, 독일어"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'sale', '"판매, 염가판매"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'rope', '밧줄');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'umbrella', '우산');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'dollar', '달러');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'mistake', '"잘못, 잘못알다"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'birth', '출생');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'pilot', '"조종사, 안내인"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'none', '아무도 ~ 않다');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'front', '"정면, 앞부분"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'present', '"현재, 선물"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'nickname', '"별명, 애칭"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'telephone', '"전화, 전화를 걸다"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'pair', '한 쌍');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'weather', '날씨');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'dish', '"접시, 요리"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'hole', '구멍');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'plane', '비행기');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'living room', '거실');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'gun', '총');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'meat', '고기');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'cover', '"덮개, 덮다"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'grass', '"풀, 잔디"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'watch', '"손목시계, 주의"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'word', '"낱말, 단어"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'explain', '설명하다');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'wear', '"입다, 착용하다"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'amuse', '재미있게 하다');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'suppose', '"상상하다, 생각하다"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'leap', '뛰다');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'bury', '묻다');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'engage', '"고용하다, 약속하다"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'sow', '씨를 뿌리다');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'lift', '들어올리다');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'bow', '"절하다, 절"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'rub', '"비비다, 문지르다"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'bite', '"물다, 물어뜯다"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'vote', '"투표하다, 투표"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'hop', '한발로 뛰다');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'imagine', '"상상하다, 생각하다"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'allow', '허락하다');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'offer', '제공하다');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'gain', '"얻다, 이기다"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'alarm', '"놀라게 하다, 경보하다"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'obey', '복종하다');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'steal', '훔치다');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'dig', '파다');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'choose', '"고르다, 선택하다"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'receive', '받다');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'bet', '돈을 걸다');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'hurt', '상처를 입히다');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'burn', '"타다, 태우다"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'sink', '가라앉다');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'decide', '"결정하다, 결심하다"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'beg', '"구걸하다, 청하다"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'reply', '"대답하다, 대답"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'tear', '"찢다, 찢어지다"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'flow', '"흐르다, 넘쳐흐르다"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'remember', '"기억하다, 생각해내다"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'appear', '"나타나다, ~인 것 같다"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'breathe', '"숨쉬다, 호흡하다"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'whistle', '"휘파람을 불다, 휘파람"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'draw', '"끌다, 당기다"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'sound', '"소리가 나다, 소리"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'save', '"구하다, 저축하다"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'continue', '계속하다');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'check', '"저지하다, 대조하다"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'sail', '"항해하다, 돛"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'wake', '"깨다, 깨우다"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'agree', '동의하다');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'hang', '"걸다, 매달다"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'record', '기록');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'drop', '"떨어지다, 떨어뜨리다"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'climb', '"기어오르다, 오르다"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'add', '"더하다, 보태다"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'shine', '빛나다');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'invite', '초대하다');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'join', '"결합하다, 참가하다"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'hide', '"감추다, 숨다"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'bring', '"가져오다, 데려오다"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'wink', '"눈을 깜박거리다, 눈짓하다"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'shoot', '"쏘다, 사격하다"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'roll', '"구르다, 굴리다"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'pull', '"잡아당기다, 끌다"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'push', '밀다');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'guess', '"추측하다, 추측"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'belong', '누구누구에게 속하다');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'happen', '"일어나다, 생기다"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'pick', '"고르다, 줍다"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'shake', '"떨다, 흔들다"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'fill', '"채우다, 가득차다"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'fail', '실패하다');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'fight', '"싸우다, 전투"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'fear', '"두려워하다, 두려움"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'carry', '"나르다, 운반하다"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'dive', '"다이빙하다, 잠수하다"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'win', '"이기다, 얻다"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'ride', '"타다, 타고 가다"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'turn', '"돌다, 변화하다,"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'need', '"필요로 하다, 필요"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'build', '"짓다, 건축하다"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'hurry', '"서두르다, 서두름"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'return', '"돌아가다, 돌아오다"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'believe', '믿다');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'suprise', '"놀라다, 놀람"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'gather', '모으다');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'throw', '던지다');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'raise', '"올리다, 일으키다"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'count', '"세다, 계산하다"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'smell', '"냄새를 맡다, 냄새"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'spend', '"소비하다, 지내다"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'pitch', '던지다');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'pop', '"펑하고 소리나다, 대중음악"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'blow', '불다');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'miss', '"놓치다, 그리워하다"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'excuse', '"용서하다, 변명하다"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'hit', '치다');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'tie', '"매다, 묶다"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'touch', '"닿다, 감동시키다"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'stay', '머무르다');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'enjoy', '즐기다');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'lose', '"잃다, 지다"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'close', '"닫다, 끝나다"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'arrive', '도착하다');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'travel', '"여행하다, 여행"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'reach', '도착하다');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'hold', '"쥐다, 계최하다"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'worry', '"걱정하다, 괴롭히다"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'marry', '결혼하다');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'expect', '"기대하다, ~라고 생각하다"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'understand', '"이해하다, 알다"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'become', '"~이 되다, 어울리다"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'break', '"부수다, 깨뜨리다"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'smoke', '"담배를 피우다, 연기"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'lend', '빌려주다');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'shut', '닫다');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'sleep', '자다');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'lay', '"눕히다, 놓다"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'paint', '"그리다, 페인트를 칠하다"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'lead', '"인도하다, 지내다"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'pass', '"지나가다, 합격하다"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'hand', '"주다, 건네주다"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'ancient', '고대의');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'nuclear', '핵의');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'necessary', '필요한');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'common', '"공통의, 보통의"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'inner', '안쪽의');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'thirsty', '목마른');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'thin', '"얇은, 야윈"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'gray', '"회색, 회색의"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'famous', '유명한');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'industrial', '"산업의, 공업의"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'silent', '"조용한, 침묵의"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'absent', '결석한');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'flat', '평평한');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'main', '주요한');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'wild', '"야생의, 난폭한"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'wet', '젖은');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'blind', '눈먼');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'dumb', '벙어리의');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'sharp', '날카로운');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'terrible', '"끔직한, 무서운"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'grand', '"웅장한,"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'homesick', '"고향을 그리워하는, 향수병의"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'bound', '~로 출발하려고 하는');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'fat', '"살찐, 지방"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'strange', '"이상한, 낯선"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'pleasant', '"기분좋은, 유쾌한"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'handsome', '"잘생긴, 멋진"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'equal', '"같은, 동등한"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'dear', '"친애하는, 값비싼"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'sweet', '달콤한');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'dull', '"우둔한, 무딘"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'weak', '약한');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'bright', '"밝은, 영리한"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'honest', '정직한');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'elder', '"손위의, 연상의"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'such', '"그러한, 이러한"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'able', '"유능한, 할 수 있는 "');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'loud', '"목소리가 큰, 시끄러운"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'simple', '"간단한, 단순한"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'clever', '영리한');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'proud', '"자랑스러운, 오만한"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'foolish', '어리석은');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'possible', '가능한');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'enough', '"충분한, 충분히"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'wise', '현명한');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'wide', '"넓은, 널리"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'successful', '성공한');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'clear', '"맑은, 명백한"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'clean', '깨끗한');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'deep', '"깊은, 깊게"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'own', '"자기 자신의, 소유하다"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'cheap', '값싼');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'certain', '"확실한, 어떤"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'important', '중요한');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'stormy', '폭풍의');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'TRUE', '진실한');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'sad', '슬픈');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'gay', '"명랑한, 화려한"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'merry', '즐거운');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'colorful', '"다채로운, 화려한"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'wonderful', '"놀랄만한, 훌률향"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'peaceful', '평화로운');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'angry', '성난');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'dry', '마른');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'wrong', '"나쁜, 틀린"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'heavy', '무거운');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'quiet', '조용한');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'several', '"여럿의, 몇몇의"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'alone', '"홀로, 다만"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'crowded', '"붐비는, 혼잡한"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'excited', '흥분한');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'alive', '살아있는');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'brown', '"갈색의, 갈색"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'different', '다른');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'difficult', '어려운');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'interesting', '재미있는');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'unlike', '같지 않은');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'least', '"가장 적은, 최소한의"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'afraid', '무서워하여');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'cool', '"서늘한, 냉정한"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'pretty', '"예쁜, 상당히"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'kind', '"친절한, 종류"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'sick', '"병든, 싫증난"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'useless', '쓸모없는');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'busy', '바쁜');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'early', '일찍이');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'past', '"과거의, ~을 지나서"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'dark', '어두운');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'cloudy', '구름이 낀');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'short', '"짧은, 키가 작은"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'low', '"낮은, 낮게"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'sincerely', '성실히');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'fortunately', '"운좋게, 다행히"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'finally', '"최후로, 마침네"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'immediately', '"곧, 즉시"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'especially', '특별히');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'else', '그밖에');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'actually', '실제로');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'hardly', '거의 ~하지 않다');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'otherwise', '다른 방법으로/ 그렇지 않으면');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'tightly', '단단히');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'recently', '최근에');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'rapidly', '"빨리, 신속히"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'however', '"아무리 ~해도, 그러나"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'politely', '"공손히, 정중하게"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'rudely', '무례하게');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'further', '"더욱이, 더먼"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'frankly', '솔직히');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'properly', '"적당히, 올바르게"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'hastely', '서둘러서');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'rather', '"오히려, 얼마간"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'together', '함께');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'altogether', '"전혀, 대체로"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'suddenly', '갑자기');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'mostly', '대개는');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'correctly', '정확히');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'ahead', '"앞으로, 앞에"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'instead', '대신에');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'quite', '"아주, 매우"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'nearly', '거의');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'badly', '"나쁘게, 몹시"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'almost', '거의');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'exactly', '정확히');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'apart', ' 따로');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'afterward', '"후에, 나중에"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'later', '"후에, 나중에"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'maybe', '아마');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'perhaps', '아마');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'probabley', '아마');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'either A and B', '"A, B 둘다"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'neigher', '~도 아니고 ~도 아니다');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'besides', '"게다가, 그밖에"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'anyway', '"어쨌든,"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'sometime', '언젠가');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'forward', '"앞쪽에, 앞으로 "');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'since', '"그 후, 그 이래"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'once', '"한번, 한때"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'twice', '두번');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'indeed', '참으로');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'seldom', '좀처럼 ~하지 않다(=harldy)');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'upside down', '거꾸로');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'whether', '~이거나 아니거나');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'unless', '~하지 않으면');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'though', '비록 ~일지라도');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'while', '~하는 동안');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'usually', '"보통, 대개"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'safely', '안전하게');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'along', '~을 따라서');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'without', '~없이');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'behind', '~의 뒤에');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'beyond', '"~의 저쪽에, ~ 이상으로"');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'below', '~의 아래에');
insert into vocabulary (word_type, word_en, word_kr) values ('M', 'toward', '~쪽으로');
